version: "3.4" 
services:
  cassandra:
      image: cassandra:latest
      container_name: cassandra
      ports: 
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
      restart: always
      environment:
         - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
         - CASSANDRA_SEEDS=127.0.0.1
      volumes:
          - ./.dev/cassandra_data:/var/lib/cassandra
      healthcheck:
          test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
          start_period: 2m
          interval: 15s
          timeout: 10s
          retries: 10
